### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter._fix'

### ISSUE THREAD

**Issue by mikewolfli** [albertosottile/py2exe#16]
Hello! I used the latest py2exe to package the py file. Meet this error: 
ModuleNotFoundError: No module named 'tkinter._fix'.  
My python version is 3.6.8. Compare the 3.4 and 3.6, I find that the tkinter._fix was remove in 3.6.
I try to revised the code of py2exe to solve the error. but failed.

**Comment by albertosottile** [comment]
Thanks for reporting this. It looks clear to me now that the tkinter hook will never work with newer Python versions. I will look for an alternative way to retrieve the tk and tcl paths as soon as I have some spare time.

**Comment by albertosottile** [comment]
Hi, this bug should be fixed now.  Can you please install the wheels from this address:
https://bintray.com/alby128/py2exe/py2exe/0.9.3.2/view/files?sort=name&order=asc#files/
and tell me if this works for you now? Thanks again for reporting this.

**Comment by Athanasius** [comment]
I can confirm this at least fixes the issue for a simple test case.  It took me a while to think to check *closed* tickets on this.  Will this version be released now ?

```#!/usr/bin/env python
import tkinter as tk

print('hello world')```

**Comment by Athanasius** [comment]
Ah, no, I see that the build process copies into lib/tcl, but the above is looking for lib/tcl8.6.  Should the copy not be stripping the version off ?

**Comment by Athanasius** [comment]
And only now do I spot the documentation on that bit of hooks.py.  So it's necessary to add the `def tk_env_paths()` to any application using tkinter, in order for the py2exe produced .exe to work ?

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. Before reopening this issue, I would like to have a reproducible example of the error. Could you please post here your script file and the `setup.py` file that caused this error? In this case, it could also be helpful to have a list of all the content of the project folder.

The `tk_env_paths` function should never be manually called because it is already executed in the bootloader of the packed executable. As a matter of fact, it would be nice if you could add a print of `os.environ["TCL_LIBRARY"]` and `os.environ["TK_LIBRARY"]` in the beginning of your script, pack it, then run again the packed executable to see if the hook worked as intended.

**Comment by Athanasius** [comment]
I'll need to expand on the very simply test case above to find the minimum that triggers the issue.  Once I have that I'll see what the environ values are coming out as.  Tomorrow.  Thanks for the speedy response.

**Comment by Athanasius** [comment]
My apologies, it turns out the project in question was specifically unsetting TCL_LIBRARY due to issues in python2.7!  So yes, the fix in 0.9.3.2 does fix the 'import tkinter' issue.
