### ISSUE TITLE
py2exe does not like anaconda's pywintypes.dll

### ISSUE THREAD

**Issue by compholio** [albertosottile/py2exe#27]
Seeing the error:
```
  File "C:\ProgramData\Miniconda3\lib\site-packages\py2exe\mf3.py", line 708, in __code__
    raise RuntimeError("should read __file__ to get the source???")
```
Which I can work around by changing:
```
                elif hasattr(self, "__file__") and not self.__file__.endswith(".pyd"):
```
to:
```
                elif hasattr(self, "__file__") and not (self.__file__.endswith(".pyd") or self.__file__.endswith(".dll")):
```

While this works, it seems odd - so I'm not sure if this is the correct solution.

**Comment by snodo** [comment]
I ran into the same issue.
My solution is very similar to yours. But I had to change another part of the code.

When py2exe was building (with option bundle_files=3), it crashed at this assertion:
...\Lib\site-packages\py2exe\runtime.py Line 506
`assert mod.__file__.endswith(EXTENSION_SUFFIXES[0])`

So I changed that assertion to an if-condition with the whole block afterwards indented.
Only 2 *.dll files (pythoncom37.dll and pywintypes37.dll) were skipped due to this change.
Those were copied afterwards by py2exe in the step "Copy ExtensionDLL" anyway.

Feels werid to do changes like this, but it worked for me.

**Comment by compholio** [comment]
Yeah, I ended up making a couple of other tweaks depending on how py2exe built certain projects, so this is what I currently have: https://github.com/sweptlaser/build-python-wine/blob/master/py2exe.diff
(against 0.9.3.1)

**Comment by albertosottile** [comment]
Hi, thanks for having reported this. In principle, building from `conda` and `virtualenv` instances is not supported, as that introduces an extra layer of complexity in the already massive world my by all the Python packages.

That being said, the fix for bugs like this should be to avoid mixing module code/binaries (.pyc and .pyd) with external libraries (.dll) in the first place. The external DLLs should never go through the module finder, that's the reason why those two calls (exception and assertion) are there. Some other part of the code (e.g. dllfinder or hooks) needs to be amended to avoid sending these paths in the module finder and instead collect these DLLs should after as ExtensionDLLs (from your comments, it seems that is working).

For these reasons, while I appreciate that you are investing time in improving `py2exe`, I do not think I will invest time in fixing this bug, for now. I am glad that you found a workaround to solve your needs, and, as usual, I would really appreciate a PR that addresses this issue as described above.

**Comment by compholio** [comment]
Okay, I have looked into this a little further and this error is occurring _because_ of a hook:
```
def hook_win32api(finder, module):
    """win32api.FindFiles(...) needs this."""
    finder.import_hook("pywintypes")
    finder.import_hook("win32timezone")
```
This causes pywintypes to be imported and because "if self.__optimize__ == sys.flags.optimize:" is not true it tries to treat the module as a source file.  That means that I can also work around this error by setting the optimization flag to match the system optimization (0).  So, I think that this says that the correct thing to do here may be to add a check to the start of Module::__code__:
```
if self.__loader__.__class__ == importlib.machinery.ExtensionFileLoader:
    return None
```
Your thoughts?

**Comment by albertosottile** [comment]
Excellent investigation, the proposed fix seems great. Have you tried it? Would you like to prepare a PR? I would be glad to review it.

**Comment by compholio** [comment]
Yup, updating it and checking it against your latest changes.  Note that it does not currently solve the other problem @snodo mentioned, but at least in my build environment that is complaining about a different DLL.
