### ISSUE TITLE
Error when building dist folder

### ISSUE THREAD

**Issue by phatberstromgg** [albertosottile/py2exe#34]
Hi @albertosottile , your project is great. Unfortunately, I have met some problems when I complied with it.  The error is: 
Building 'dist\app.exe'.
error: [WinError 87] The parameter is incorrect.

My setup.py file contains:

from distutils.core import setup
import py2exe
setup (windows = [{"script":'app.py', "icon_resources":[(1,"0.png")]}])

My pip list:

Click           7.0
cycler          0.10.0
decorator       4.4.1
filterpy        1.4.5
fire            0.2.1
Flask           1.1.1
Flask-Cors      3.0.8
imageio         2.6.1
itsdangerous    1.1.0
Jinja2          2.10.3
joblib          0.14.0
kiwisolver      1.1.0
llvmlite        0.30.0
MarkupSafe      1.1.1
matplotlib      3.1.2
networkx        2.4
numba           0.46.0
numpy           1.17.4
opencv-python   4.1.2.30
pandas          0.25.3
Pillow          6.2.1
pip             19.2.3
py2exe          0.9.3.2
pyparsing       2.4.5
PyQt5           5.13.2
PyQt5-sip       12.7.0
pytesseract     0.3.0
python-dateutil 2.8.1
pytz            2019.3
PyWavelets      1.1.1
PyYAML          5.2
scikit-image    0.16.2
scikit-learn    0.21.3
scipy           1.3.3
setuptools      41.2.0
six             1.13.0
termcolor       1.1.0
terminaltables  3.1.0
torch           1.3.1
torchvision     0.4.2
tqdm            4.40.0
Werkzeug        0.16.0

How I can solve this. Hope to hear from you soon. Thank you.

**Comment by albertosottile** [comment]
To debug this, I would need to have access to the `app.py` script. In the meantime, I would encourage you to try again with a newer version (0.10.0.1 has been released recently).

**Comment by albertosottile** [comment]
Closing this as nothing new happened in the past weeks. Please feel free to reopen anytime.

**Comment by dmeklund** [comment]
For anyone coming here from a search, I ran into this error message when attempting to run py2exe on a trivial input python file because I was running in a virtual environment that had been created from a Python version that had since been uninstalled. Recreating the virtual environment with the newly installed version of Python resolved the issue.

**Comment by Dsolnik** [comment]
For anyone else coming here from a search. I ran into this problem when trying to run py2exe using a version of python supported by py2exe (3.8) though my system default was 3.9. I could not use 3.9 because py2exe doesn't support Python 3.9 yet.

I created a python 3.8 virtual environment and was able to run py2exe in that.
